const state = { mode: 'live', section: 'overview', overview: null, transactions: [], selectedAlert: null, network: null, trail: null };
const scenarios = [
  ['legitimate_growth', 'Legitimate growth', 'Anomaly rises while corroborating risk stays stable.'],
  ['abuse_ring', 'Coordinated fraud', 'Shared entities, failed payments, and velocity compound.'],
  ['account_takeover', 'Account takeover', 'New device and behavior change on a trusted account.'],
  ['fraud_escalation', 'Fraud escalation', 'Risk transitions as evidence accumulates.'],
  ['cash_out', 'Cash-out scenario', 'Observable digital trail ends at cash withdrawal.'],
  ['suspicious_transaction', 'Suspicious transaction', 'Large amount and repeated attempts require review.'],
  ['cross_border_anomaly', 'International anomaly', 'Cross-border context adds evidence, not proof.'],
  ['slow_fraud', 'Slow gradual fraud', 'Low-volume signals accumulate over time.'],
  ['distributed_fraud', 'Distributed fraud', 'Small increases spread across linked entities.'],
  ['vpn_legitimate', 'Legitimate VPN', 'VPN remains weak context around trusted behavior.'],
  ['frequent_ip_changes', 'Frequent IP changes', 'IP movement alone remains weak evidence.'],
  ['false_positive', 'False positive', 'Unusual but verified legitimate behavior.'],
  ['false_negative', 'False negative', 'Fraud pattern initially resembles normal activity.'],
  ['fraud_adaptation', 'Fraud adaptation', 'Changed strategy is not permanently trusted.'],
  ['insufficient_evidence', 'Insufficient evidence', 'Ambiguous signals stay uncertain.']
];
const nav = [['overview','Overview'],['transactions','Transactions'],['alerts','Risk alerts'],['investigation','Investigation'],['network','Entity network'],['trail','Money trail'],['demo','Demo / simulation'],['model','Model performance'],['health','System health']];
const API_BASE = globalThis.RISKORA_API_BASE || '';
const api = async (path, options = {}) => { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 10000); try { const response = await fetch(`${API_BASE}/api${path}`, { headers: {'Content-Type':'application/json'}, signal: controller.signal, ...options }); if (!response.ok) { let detail = `Request failed (${response.status})`; try { const body = await response.json(); detail = body.detail || detail; } catch {} throw new Error(detail); } return response.json(); } finally { clearTimeout(timeout); } };
const money = value => `₹${Number(value || 0).toLocaleString('en-IN', {maximumFractionDigits: 0})}`;
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge = level => `<span class="badge ${level === 'LOW' ? 'low' : level === 'MEDIUM / UNCERTAIN' ? 'medium' : level === 'CRITICAL' ? 'critical' : ''}">${esc(level)}</span>`;
function renderError(error) { const message = error?.name === 'AbortError' ? 'The Riskora API took too long to respond.' : (error?.message || 'Unexpected application error.'); document.getElementById('app').innerHTML = `<div class="empty error-state" role="alert"><strong>Riskora could not complete that request.</strong><span>${esc(message)}</span><button class="primary" onclick="window.location.reload()">Retry</button></div>`; }
window.addEventListener('error', event => renderError(event.error));
window.addEventListener('unhandledrejection', event => renderError(event.reason));

async function refresh() {
  state.overview = await api(`/overview?mode=${state.mode}`);
  state.transactions = await api(`/transactions?mode=${state.mode}`);
  if (state.mode === 'demo' && state.overview.alerts?.length && !state.selectedAlert) state.selectedAlert = state.overview.alerts[0];
  if (state.mode === 'demo' && state.selectedAlert) await loadNetwork();
  if (state.section === 'network' && state.selectedAlert) await loadNetwork();
  if (state.section === 'trail' && state.selectedAlert) await loadTrail();
  await render();
}
function shell(content) {
  const activeNav = nav.map(([id,label]) => `<button class="${state.section === id ? 'active' : ''}" data-section="${id}">${label}</button>`).join('');
  const mobile = nav.map(([id,label]) => `<button class="${state.section === id ? 'active' : ''}" data-section="${id}">${label}</button>`).join('');
  return `<div class="shell"><header class="topbar"><div class="brand"><div class="mark">R</div><div><strong>RISKORA</strong><small>Risk intelligence / local</small></div></div><div class="mode"><button class="${state.mode === 'live' ? 'active live' : ''}" data-mode="live">LIVE</button><button class="${state.mode === 'demo' ? 'active demo' : ''}" data-mode="demo">DEMO</button></div></header><div class="layout"><aside class="sidebar"><div class="nav-title">Control room</div><nav class="nav">${activeNav}</nav><div class="panel" style="margin-top:30px"><div class="eyebrow">Data boundary</div><p class="subtle">Demo data never mixes with the live ingestion store. Risk colors show status, not certainty.</p></div></aside><main><div class="mobile-nav">${mobile}</div><div class="page-head"><div><div class="eyebrow">${state.mode === 'live' ? 'Live / connected mode' : 'Demo / simulated event stream'}</div><h1>${nav.find(x => x[0] === state.section)?.[1] || 'Overview'}</h1></div><div class="clock">UTC event clock<br><strong>${new Date().toLocaleTimeString()}</strong></div></div>${content}</main></div></div>`;
}
function timeline(points, events) {
  if (!points?.length) return `<div class="empty">Live state is genuinely empty.<br>Post an event or run a demo scenario.</div>`;
  const pointXY = (point, index) => ({ x: 42 + (points.length < 2 ? 460 : index * 900 / (points.length - 1)), y: 20 + (100 - point.risk_score) * 2.2 });
  const risk = points.map((p, i) => { const a = pointXY(p, i); return `${a.x},${a.y}`; }).join(' ');
  const anomaly = points.map((p, i) => { const a = pointXY({risk_score:p.anomaly_percentage}, i); return `${a.x},${a.y}`; }).join(' ');
  const dots = points.map((p,i) => { const a=pointXY(p,i); return `<circle cx="${a.x}" cy="${a.y}" r="4" fill="#f3f7f4"><title>${new Date(p.timestamp).toLocaleTimeString()} · Risk ${p.risk_score} · Anomaly ${p.anomaly_percentage}% · Activity ${money(p.transaction_activity)}</title></circle>`; }).join('');
  const markers = (events || []).map(e => { const i=points.findIndex(p=>p.timestamp===e.timestamp); if(i<0)return ''; const a=pointXY(points[i],i); return `<line x1="${a.x}" y1="20" x2="${a.x}" y2="240" stroke="#f17676" stroke-dasharray="3 5"/><circle cx="${a.x}" cy="${a.y}" r="8" fill="none" stroke="#f17676"><title>${esc(e.event)} · ${esc(e.evidence)}</title></circle>`; }).join('');
  return `<div class="timeline-wrap"><svg viewBox="0 0 980 300" role="img" aria-label="Risk score and anomaly percentage over time"><rect x="42" y="20" width="920" height="220" fill="none" stroke="#252a2a"/><rect x="42" y="20" width="920" height="77" fill="#4c171e" opacity=".16"/><rect x="42" y="97" width="920" height="66" fill="#8d6a18" opacity=".08"/><line x1="42" x2="962" y1="97" y2="97" stroke="#f17676" stroke-dasharray="5 6"/><line x1="42" x2="962" y1="163" y2="163" stroke="#e7b769" stroke-dasharray="5 6"/><polyline points="${anomaly}" fill="none" stroke="#e7b769" stroke-width="2" stroke-dasharray="5 4"/><polyline points="${risk}" fill="none" stroke="#f3f7f4" stroke-width="3"/>${markers}${dots}<text x="48" y="34" fill="#f17676" font-size="10">HIGH / CRITICAL</text><text x="48" y="111" fill="#e7b769" font-size="10">MEDIUM</text><text x="42" y="262" fill="#7f8b88" font-size="10">OLDER EVENTS</text><text x="890" y="262" fill="#7f8b88" font-size="10">NOW</text></svg></div>`;
}
function networkPreview() {
  const n = state.network;
  if (!n) return `<div class="empty graph-empty">${state.mode === 'live' ? 'No live entities yet — the graph activates after a local ingestion event.' : 'Synthetic graph data is loading.'}</div>`;
  const positions = n.nodes.map((node, i) => ({...node, x: 90 + (i % 4) * 190, y: 90 + Math.floor(i / 4) * 100}));
  const lines = n.edges.map(edge => { const s=positions.find(x=>x.id===edge.source_entity), t=positions.find(x=>x.id===edge.target_entity); return s&&t ? `<line x1="${s.x}" y1="${s.y}" x2="${t.x}" y2="${t.y}" stroke="${edge.risk_contribution >= 65 ? '#f17676' : '#476361'}" stroke-width="${edge.risk_contribution >= 65 ? 3 : 1.5}"/>` : ''; }).join('');
  const nodes = positions.map(node => `<g><circle cx="${node.x}" cy="${node.y}" r="24" fill="#111313" stroke="${node.risk_score >= 65 ? '#f17676' : node.risk_score >= 35 ? '#e7b769' : '#74d69c'}" stroke-width="2"/><text x="${node.x}" y="${node.y+3}" fill="#f3f7f4" font-size="9" text-anchor="middle">${esc(node.id.slice(0,12))}</text><text x="${node.x}" y="${node.y+39}" fill="#7f8b88" font-size="8" text-anchor="middle">risk ${node.risk_score}</text></g>`).join('');
  return `<div class="graph-preview"><svg viewBox="0 0 700 230" role="img" aria-label="Synthetic entity relationship graph">${lines}${nodes}</svg></div>`;
}
function overview() {
  const o=state.overview||{}; const alerts=(o.alerts||[]).slice(0,6).map(a=>`<div class="alert" data-alert="${esc(a.transaction_id)}"><div><strong>${esc(a.transaction_id)}</strong><div class="subtle">${esc(a.entity)} · ${esc(a.recommended_action)}</div></div><div>${badge(a.risk_level)}<div class="subtle">${money(a.estimated_exposure)}</div></div></div>`).join('');
  return `<div class="cards"><div class="card"><label>Total transactions</label><div class="value">${o.total_transactions||0}</div><div class="subtle">${state.mode==='live'?'Only live events':'Synthetic scenario events'}</div></div><div class="card"><label>High-risk events</label><div class="value" style="color:var(--red)">${o.high_risk_events||0}</div><div class="subtle">${o.medium_risk_events||0} medium / uncertain</div></div><div class="card"><label>Estimated exposure</label><div class="value" style="color:var(--amber)">${money(o.estimated_exposure)}</div><div class="subtle">Risk × amount estimate</div></div><div class="card"><label>Current risk</label><div class="value" style="color:var(--cyan)">${o.current_risk||0}<small>/100</small></div><div class="subtle">Trend ${o.risk_trend>0?'+':''}${o.risk_trend||0}</div></div></div><section class="panel timeline-panel"><div class="panel-head"><div><div class="eyebrow">Risk / behavior over time</div><h2>Trading-style risk timeline</h2></div><div class="chart-key"><span class="risk-key">● Risk score</span><span class="anomaly-key">● Anomaly %</span><span>○ Risk event</span></div></div>${timeline(o.timeline,o.events)}<div class="timeline-footer"><span>Current value: <b>${o.current_risk||0}/100</b></span><span>Anomaly is not probability of fraud</span><span>Events: ${(o.events||[]).length}</span></div></section><section class="panel graph-panel"><div class="panel-head"><div><div class="eyebrow">Relationship intelligence</div><h2>${state.mode==='demo'?'Synthetic entity graph':'Live entity graph'}</h2></div><button class="text-button" data-section="network">Open full graph →</button></div>${networkPreview()}<p class="subtle">${state.mode==='demo'?'Generated from the selected synthetic scenario. Shared infrastructure is evidence, not proof.':'No live graph is fabricated. Ingest a local event to create live relationships.'}</p></section><div class="dashboard"><section class="panel"><div class="panel-head"><div><div class="eyebrow">Priority queue</div><h2>Recent risk alerts</h2></div><button class="text-button" data-section="alerts">View all →</button></div>${alerts||`<div class="empty">No ${state.mode} alerts in this mode.</div>`}</section><section class="panel context"><div class="eyebrow">Context readout</div><h2>${state.mode==='live'?'Connected mode':'Scenario mode'}</h2><p>${state.mode==='live'?(o.total_transactions?'Live values are sourced from the local ingestion API.':'Live state is genuinely empty. No external Razorpay credentials or data are used.'):'Synthetic events use the same backend scorer as live ingestion. Open an alert to inspect evidence, linked entities, and observable money movement.'}</p></section></div>`;
}
function transactions() {
  const rows = state.transactions.map(t => `<tr><td>${esc(t.transaction_id)}</td><td>${new Date(t.timestamp).toLocaleTimeString()}</td><td>${money(t.amount)}</td><td>${badge(t.risk.risk_level)}</td><td>${t.risk.anomaly_percentage}%</td><td>${esc(t.payment_method)}</td></tr>`).join('');
  return `<p class="section-copy">${state.mode === 'live' ? 'Only events posted to the backend ingestion endpoint appear here. Empty is a valid state.' : 'Synthetic transactions generated by the backend scenario runner.'}</p>${state.mode === 'live' ? `<section class="panel" style="margin:20px 0"><div class="eyebrow">Post a live test event</div><div class="form" style="margin-top:14px"><input id="amount" aria-label="Transaction amount" type="number" min="1" value="2500" placeholder="Amount"/><input id="customer" aria-label="Customer ID" value="cus_live_001" placeholder="Customer ID"/><input id="device" aria-label="Device ID" value="dev_known_001" placeholder="Device ID"/><button class="primary" id="ingest">Ingest event</button></div></section>` : ''}${rows ? `<section class="panel"><table class="table"><thead><tr><th>Transaction</th><th>Time</th><th>Amount</th><th>Risk</th><th>Anomaly</th><th>Method</th></tr></thead><tbody>${rows}</tbody></table></section>` : `<div class="empty" style="margin-top:20px">No transactions in this mode.</div>`}`;
}
function alerts() { const rows = (state.overview?.alerts || []).map(a => `<div class="alert"><div><strong>${esc(a.transaction_id)}</strong><div class="subtle">${esc(a.evidence?.join(' · ') || 'Review evidence')}</div></div><div>${badge(a.risk_level)}<div class="subtle">Risk ${a.risk_score}/100 · ${money(a.estimated_exposure)}</div></div></div>`).join(''); return `<p class="section-copy">Alerts separate anomaly, risk, and confidence. Signals are evidence, not certainty.</p><section class="panel" style="margin-top:20px">${rows || '<div class="empty">No active alerts in this mode.</div>'}</section>`; }
function investigation() { const a=state.selectedAlert; if(!a) return `<p class="section-copy">Select an alert to inspect evidence, financial exposure, entity relationships, and a verified outcome.</p><div class="empty">No alert selected.</div>`; return `<div class="investigation-grid"><section><div class="panel risk-summary"><div class="eyebrow">Evidence-led review</div><div class="summary-row"><div><h2>${esc(a.transaction_id)}</h2><div class="subtle">Entity ${esc(a.entity)} · Prediction ≠ ground truth</div></div>${badge(a.risk_level)}</div><div class="metric-strip"><div><label>Risk</label><b>${a.risk_score}/100</b></div><div><label>Confidence</label><b class="cyan">${a.confidence_score}%</b></div><div><label>Anomaly</label><b class="amber">${a.anomaly_percentage}%</b></div><div><label>Urgency</label><b class="red">${a.urgency}</b></div></div></div><div class="panel"><div class="eyebrow">Contributing evidence</div><div class="evidence-list">${(a.evidence||[]).map((x,i)=>`<div><span>0${i+1}</span>${esc(x)}</div>`).join('')}</div><p class="callout">Riskora does not treat one signal as proof. Validate evidence against linked entities and verified outcomes.</p></div></section><aside><div class="panel"><div class="eyebrow">Estimated exposure</div><div class="exposure">${money(a.estimated_exposure)}</div><div class="subtle">Risk probability × amount estimate</div><div class="action-box">${esc(a.recommended_action)}</div><button class="primary full" data-open-network>Inspect entity network</button><button class="secondary full" data-open-trail>Reconstruct money trail</button></div><div class="panel"><div class="eyebrow">Verified outcome</div><p class="subtle">Only analyst-verified outcomes are feedback. Predictions never silently retrain the model.</p><div class="outcomes"><button data-outcome="CONFIRMED FRAUD">Confirm fraud</button><button data-outcome="LEGITIMATE">Mark legitimate</button><button data-outcome="UNCERTAIN">Keep uncertain</button></div></div></aside></div>`; }
async function loadNetwork(){ const id=state.selectedAlert?.entity; if(id) state.network=await api(`/entities/${encodeURIComponent(id)}/network?mode=${state.mode}`); }
async function loadTrail(){ const id=state.selectedAlert?.transaction_id; if(id) state.trail=await api(`/transactions/${encodeURIComponent(id)}/money-trail?mode=${state.mode}`); }
function network(){ const n=state.network; if(!n)return `<p class="section-copy">Select an alert, then inspect its connected customer, device, network, instrument, merchant, and beneficiary.</p><div class="empty">No entity network selected.</div>`; const positions=n.nodes.map((node,i)=>({...node,x:120+(i%3)*250,y:100+Math.floor(i/3)*150})); const lines=n.edges.map(e=>{const s=positions.find(x=>x.id===e.source_entity),t=positions.find(x=>x.id===e.target_entity);return s&&t?`<line x1="${s.x}" y1="${s.y}" x2="${t.x}" y2="${t.y}" stroke="${e.risk_contribution>=65?'#f17676':'#476361'}" stroke-width="${e.risk_contribution>=65?3:1.5}"/><text x="${(s.x+t.x)/2}" y="${(s.y+t.y)/2-7}" fill="#7f8b88" font-size="9">${esc(e.relationship_type)}</text>`:''}).join(''); const circles=positions.map(n=>`<g><circle cx="${n.x}" cy="${n.y}" r="28" fill="#111313" stroke="${n.risk_score>=65?'#f17676':n.risk_score>=35?'#e7b769':'#74d69c'}" stroke-width="2"/><text x="${n.x}" y="${n.y+3}" fill="#f3f7f4" font-size="10" text-anchor="middle">${esc(n.id.slice(0,14))}</text><text x="${n.x}" y="${n.y+45}" fill="#7f8b88" font-size="9" text-anchor="middle">risk ${n.risk_score}</text></g>`).join(''); return `<p class="section-copy">Shared infrastructure is a relationship signal, not automatic proof of fraud. Red edges indicate contribution, not certainty.</p><section class="panel network-panel"><svg viewBox="0 0 720 430" aria-label="Entity relationship network">${lines}${circles}</svg><div class="network-legend">${n.nodes.map(x=>`<span>${esc(x.id)} · risk ${x.risk_score}</span>`).join('')}</div></section>`; }
function trail(){ const t=state.trail; if(!t)return `<p class="section-copy">Money trail reconstruction shows observable digital movement only. It does not infer physical location or promise cash recovery.</p><div class="empty">No money trail selected.</div>`; return `<p class="section-copy">Observable movement for ${esc(t.transaction_id)}. The digital trace ends when a cash withdrawal is observed.</p><section class="panel trail-panel"><div class="trail-flow">${t.nodes.map((n,i)=>`${i?'<span class="arrow">→</span>':''}<div class="trail-node ${n.type==='CASH-OUT'?'cash':''}"><label>${esc(n.type)}</label><strong>${esc(n.label)}</strong><span>${n.amount?money(n.amount):''}</span><small>${esc(n.status)}</small></div>`).join('')}</div>${t.notice?`<div class="cash-notice">${esc(t.notice)}</div>`:''}<div class="trail-ledger">${t.edges.map(e=>`<div><span>${esc(e.source)} → ${esc(e.target)}</span><small>${esc(e.description)}</small><b>${money(e.amount)}</b></div>`).join('')}</div></section>`; }
function demo() { return `<p class="section-copy">Run a controlled backend scenario. It clears only DEMO data, runs the shared risk engine, and refreshes the dashboard. Start with Legitimate Growth to see elevated anomaly without high risk.</p><div class="scenario-grid" style="margin-top:22px">${scenarios.map(([id,title,desc]) => `<button class="scenario" data-scenario="${id}"><h3>${title}</h3><p>${desc}</p><div class="eyebrow">Backend scenario runner →</div></button>`).join('')}</div>`; }
async function model() { const m = await api('/model/metrics'); const cm=m.confusion_matrix||{}; return `<div class="cards"><div class="card"><label>Precision</label><div class="value">${(m.precision*100).toFixed(1)}%</div><div class="subtle">Positive predictions correct</div></div><div class="card"><label>Recall</label><div class="value" style="color:var(--amber)">${(m.recall*100).toFixed(1)}%</div><div class="subtle">Fraud labels found</div></div><div class="card"><label>F1</label><div class="value">${(m.f1*100).toFixed(1)}%</div><div class="subtle">Precision / recall balance</div></div><div class="card"><label>PR-AUC</label><div class="value" style="color:var(--green)">${m.pr_auc}</div><div class="subtle">Ranking quality</div></div></div><section class="panel"><div class="eyebrow">Actual calculated evaluation</div><h2>Time-aware held-out model</h2><p class="section-copy">${esc(m.methodology)} Metrics are synthetic and illustrative, not Razorpay production metrics.</p><div class="metric-strip"><div><label>False positive rate</label><b>${(m.false_positive_rate*100).toFixed(1)}%</b></div><div><label>False negative rate</label><b>${(m.false_negative_rate*100).toFixed(1)}%</b></div><div><label>Dataset</label><b>${m.dataset_size} rows</b></div></div><div class="confusion"><span>TP ${cm.true_positives||0}</span><span>TN ${cm.true_negatives||0}</span><span class="red">FP ${cm.false_positives||0}</span><span class="amber">FN ${cm.false_negatives||0}</span></div></section>`; }
async function health() { const h = await api(`/system/health?mode=${state.mode}`); return `<div class="cards"><div class="card"><label>API</label><div class="value" style="color:var(--green)">${h.api_status}</div><div class="subtle">Backend responding</div></div><div class="card"><label>Database</label><div class="value" style="font-size:20px">${h.database_status}</div><div class="subtle">Mongo-ready memory fallback</div></div><div class="card"><label>Risk engine</label><div class="value" style="color:var(--green)">${h.risk_engine_status}</div><div class="subtle">Shared pipeline</div></div><div class="card"><label>Mode</label><div class="value" style="color:var(--cyan)">${h.mode.toUpperCase()}</div><div class="subtle">Selected context</div></div></div>`; }
async function render() { let content = state.section === 'overview' ? overview() : state.section === 'transactions' ? transactions() : state.section === 'alerts' ? alerts() : state.section === 'investigation' ? investigation() : state.section === 'network' ? network() : state.section === 'trail' ? trail() : state.section === 'demo' ? demo() : state.section === 'model' ? await model() : await health(); document.getElementById('app').innerHTML = shell(content); bind(); }
function bind() { document.querySelectorAll('[data-mode]').forEach(b => b.onclick = async () => { state.mode = b.dataset.mode; state.section = 'overview'; state.selectedAlert = null; state.network = null; state.trail = null; await refresh(); }); document.querySelectorAll('[data-section]').forEach(b => b.onclick = async () => { state.section = b.dataset.section; if (state.section === 'network' && state.selectedAlert) await loadNetwork(); if (state.section === 'trail' && state.selectedAlert) await loadTrail(); await render(); }); document.querySelectorAll('[data-alert]').forEach(b => b.onclick = async () => { state.selectedAlert = (state.overview.alerts || []).find(a => a.transaction_id === b.dataset.alert) || null; state.section = 'investigation'; await render(); }); document.querySelectorAll('[data-scenario]').forEach(b => b.onclick = async () => { b.disabled = true; await api('/simulation/scenario', {method:'POST',body:JSON.stringify({scenario:b.dataset.scenario})}); state.mode='demo'; state.section='overview'; await refresh(); }); const ingest = document.getElementById('ingest'); if (ingest) ingest.onclick = async () => { await api('/transactions', {method:'POST',body:JSON.stringify({amount:Number(document.getElementById('amount').value),customer_id:document.getElementById('customer').value,device_id:document.getElementById('device').value})}); await refresh(); }; const openNetwork=document.querySelector('[data-open-network]'); if(openNetwork) openNetwork.onclick=async()=>{await loadNetwork();state.section='network';await render();}; const openTrail=document.querySelector('[data-open-trail]'); if(openTrail) openTrail.onclick=async()=>{await loadTrail();state.section='trail';await render();}; document.querySelectorAll('[data-outcome]').forEach(b=>b.onclick=async()=>{if(state.selectedAlert?.investigation_id){await api(`/investigations/${state.selectedAlert.investigation_id}/outcome`,{method:'POST',body:JSON.stringify({outcome:b.dataset.outcome,confidence:92,analyst_note:'Verified during Riskora analyst review.'})});await refresh();}}); }
refresh().catch(renderError);
